db:
  host: localhost
  port: 8010
  user: admin
  password: gin-template123
  name: gin-template

gin-port: 8080

zap:
  level: info
  format: console
  prefix: "[gin-template]"
#  director: log 执行路径目前
  director: ./log
  show-line: true
  encode-level: "LowercaseColorLevelEncoder"
  stacktrace-key: stacktrace
  log-in-console: true
