package main

import (
	"fmt"
	"gin-template/config"
	"gin-template/database"
	"gin-template/docs" // docs are generated by Swag CLI, you have to import it.
	"gin-template/routing"
	"github.com/gin-gonic/gin"
	swaggerfiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func main() {

	database.ConnectDB()

	router := gin.Default()
	docs.SwaggerInfo.BasePath = "/api/v1"
	router.Use(gin.Logger())
	routing.Setup(router)
	err := router.Run(fmt.Sprintf(":%s", config.Config.Port))
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))
	if err != nil {
		return
	}
}
