package main

import (
	"fmt"
	"gin-template/config"
	"gin-template/database"
	_ "gin-template/docs" // docs are generated by Swag CLI, you have to import it.
	"gin-template/routing"
	"github.com/gin-gonic/gin"
)

func main() {

	database.ConnectDB()

	router := gin.Default()
	router.Use(gin.Logger())
	routing.Setup(router)
	err := router.Run(fmt.Sprintf(":%s", config.Config.Port))
	if err != nil {
		return
	}
}
